services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: nocodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - 8180:8080
    environment:
      NC_DB: "pg://postgres:5432?u=admin&p=admin&d=nocodb"
      NC_AUTH_JWT_SECRET: "569a1821-0a93-45e8-87ab-eb857f20a010"
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local